name: Build using Intel OneAPI components
description: Build codes using Intel OneAPI components on github actions
author: 'Dr. Ravindra Shinde'
branding:
  icon: 'code'
  color: 'orange'

inputs:
  basekit:
    description: 'Install Intel OneAPI Base Toolkit'
    required: true
    default: 'true'
  hpckit:
    description: 'Install Intel OneAPI HPC Toolkit'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download Intel oneAPI
      if: runner.os == 'Linux'
      id: download
      shell: bash
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt-get update

    - name: Cache Intel oneAPI components
      uses: actions/cache@v2
      with:
        path: /opt/intel
        key: ${{ runner.os }}-oneapi
        restore-keys: |
          ${{ runner.os }}-oneapi

    - name: Install Intel oneAPI Base Toolkit
      if: inputs.basekit == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-common-vars
        sudo apt-get install -y intel-oneapi-compiler-fortran-2021.3.0
        sudo apt-get install -y intel-oneapi-mkl-2021.3.0
        sudo apt-get install -y intel-oneapi-mkl-devel-2021.3.0
        source /opt/intel/oneapi/setvars.sh

    - name: Install Intel oneAPI HPC Toolkit
      if: inputs.hpckit == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-mpi-2021.3.0
        sudo apt-get install -y intel-oneapi-mpi-devel-2021.3.0
        source /opt/intel/oneapi/setvars.sh